#!/bin/bash
#
# bin:   Classify a list of lines of string in the clipboard &
# 	print the output.
# 

n0=0
n=1
i=0
str=$(pbpaste | tr -sc '[A-z0-9\n]' '\n' | sed 's/$/,/' | sort);

while [[ ! n0 -eq n ]] && [[ i -lt 20 ]]; do { 
	i=$[ i + 1 ];
	n0=$(echo "$str" | wc -l);
	str=$(echo "$str" | perl -0777 -pe 's/^([^\n\t\+]+)(\+*)\n\1/\1\2+/gm');
	n=$(echo "$str" | wc -l);
	# echo "$n0/$n";
}; done


stars_num=$(echo "$str" | gsed 's/\+/+\n/g' | grep -c '+')
# echo "stars_num: <$stars_num>"
str_final=""
export IFS="|"
for i in $(echo $str | tr -s '\n' '|'); do {
	n_line=$(echo "$i" | gsed 's/\+/+\n/g' | grep -c '+');
	n_line_perc=$(echo "100*$n_line/$stars_num" | bc);
	# n_line_perc=5
	s=$(printf "%-${n_line_perc}s" '-');
	rep=$(echo ${s// /-});
	# echo $s;
	# echo $n_line_perc;
	i_final=$(echo $i | gsed "s/,.*$/,$rep/");
	str_final+="$i_final\n";
	# echo $str_final;
}; done

printf "$str_final" | xsv table
