#!/bin/bash
#
# bin:   Create a histogram of non-common words in a string input.
#				!important: Data is pasted from the clipboard.
# 
# REQUIREMENTS: gsed
# 

related="$(< /dev/stdin)";

n0=0
n=1
i=0
str=$(echo -e "$related" | tr -sc '[A-z0-9\n]' '\n' | sed 's/$/,/' | sort);
mcf="$(pwd)/data/common_words.txt"
most_common=$(cat $mcf | tr -s '\n' '|' | gsed 's/|/\\|/g')

while [[ ! n0 -eq n ]] && [[ i -lt 20 ]]; do { 
	i=$[ i + 1 ];
	n0=$(echo "$str" | wc -l);
	str=$(echo "$str" | perl -0777 -pe 's/^([^\n\t\+]+)(\+*)\n\1/\1\2+/gm');
	n=$(echo "$str" | wc -l);
	# echo "$n0/$n";
}; done

# echo "$str" | gsed "s/^\(${most_common::${#most_common}-1}\),.*$//i"
echo "$str" |
	gsed "s/^\(${most_common::${#most_common}-1}}\),.*$//i" |
	sort |
	uniq;

