#!/bin/bash
# 
# explode:   Convert a spreadsheet file (xls, xlsx, ods, etc.)
#				into csv files (one file per sheet)
# 
# REQUIREMENTS:	ssconvert (from LibreOffice)
# 		rename (from util-linux)
# 
# TODO: use sheet names to rename csv files
# 

help_string="
$bold explode$blank: Convert a spreadsheet file (xls, xlsx, ods, etc.) into csv files (one file per sheet)

$yellow USAGE: $blank
    $bold explode $blank [flags/options] [filename]

$yellow FLAGS: $blank
    $green -c   $blank .
    $green -h   $blank show list of command-line options.
"

while getopts 'h-:' opt; do
    case "${opt}" in
    h|\?) printf "$help_string"; b_help="help"; exit 1;;
    -) if [[ $OPTARG == "help" ]]; then printf "$help_string"; b_help="help"; exit 1; fi; ;;
    *) echo "Unknown flag $OPTARG."; exit 1;;
  esac
done

q="$1";
ssconvert -S "$q" "$q.csv";
rename -e "s/\.\w+\.csv\.(\d+)$/_\$1.csv/" *.csv*;
