#!/bin/bash
# 
# implode:   Combine all csv files in the current directory
#				into a spreadsheet (xls, xlsx, ods, etc.)
# 
# REQUIREMENTS:	ssconvert (from LibreOffice)
# 

help_string="
$bold implode$blank: Combine all csv files in the current directory into a spreadsheet (xls, xlsx, ods, etc.)

$yellow USAGE: $blank
    $bold implode $blank [flags/options] [filename]

$yellow FLAGS: $blank
    $green -c   $blank .
    $green -h   $blank show list of command-line options.
"

while getopts 'h-:' opt; do
    case "${opt}" in
    h|\?) printf "$help_string"; b_help="help"; exit 1;;
    -) if [[ $OPTARG == "help" ]]; then printf "$help_string"; b_help="help"; exit 1; fi; ;;
    *) echo "Unknown flag $OPTARG."; exit 1;;
  esac
done

q="$1";
ssconvert $(ls *csv) -M "$q";
