#!/bin/bash
#
# command:  print a list of todos.
# 
# REQUIREMENTS: req1, re2, req3
# 

q="$BASH_ARGV";
debug=0;
help_string="
$bold command$blank: Lorem ipsum dolor sit amet consectetur adipiscing.

$yellow USAGE: $blank
    $bold command $blank [flags/options] [query]

$yellow FLAGS: $blank
    $green -c   $blank risus torquent congue venenatis.
    $green -h   $blank show list of command-line options.

"

while getopts 'h-:' opt; do
    case "${opt}" in
		d) debug=1;;
	    h|\?) printf "$help_string"; b_help="help"; exit 1;;
	    -) if [[ $OPTARG == "help" ]]; then printf "$help_string"; b_help="help"; exit 1; fi; ;;
	    *) echo "Unknown flag $OPTARG."; exit 1;;
	esac
done

datadir="$DATAPATH"
if [[ -z "$datadir" ]]; then datadir=$(pwd); fi

if [[ "$debug" == 1 ]]; then {
	echo "debugging";
}; fi



red="\e[0;31m"; green="\e[0;32m"; yellow="\e[0;33m"; blue="\e[0;34m"; magenta="\e[0;35m"; purple="\e[0;36m"; white="\e[0;37m"; grey_light="\e[0;38m"; grey="\e[0;39m"; red_light="\e[1;31m"; green_light="\e[1;32m"; yellow_light="\e[1;33m"; blue_light="\e[1;34m"; magenta_light="\e[1;35m"; purple_light="\e[1;36m"; blank="\e[m";
function todo_splt(){ n="$1";
	if [[ -n $1 ]]; then {
		sig=${n:0:3}; frog=$(echo ${n:4:3} | rev); time=${n:8:3}; comp=${n:12:5}; emoj=${n:18:1}; cap=${n:19:1}; acry=${n:20:1}; desc=${n:23};
		printf "$sig $green$acry$blank $frog $comp $time $emoj\\t$cap$desc\n";
	}; fi; }
file="~/.local/todos/todos.md";
n0=$(grep -n '⿶' $file | cut -d : -f1); n0=$[ n0 + 1 ];
n1=$(grep -n '⿵' $file | cut -d : -f1); n1=$[ n1 - 1 ];
res=""; IFS=$'\n';read -rd '' -a y <<< "$(sed "$n0,$n1 p;d" $file)";
for l in ${y[@]}; do { res="$res\n$(todo_splt $l)"; }; done
# res=$( | gsed "s/\// \\$red||\\$blank /g" | gsed "s/^\(...\) \(...\) \(...\) \(.....\) \(.*\) \(\w\): / \1 \\$green\6\\$blank \3 \5\\t/")
# nf=$(printf "$res" | grep -m1 -n '\-\-\-\-\-' | gsed 's/:\-*$//');
# nf=$[ $nf - 2 ];

printf "$res" | tail -n +2 | sort -r;
